// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn1-Qg3_nK9YN-nwGwWN8gjeO9-d68hsQ',
    appId: '1:281641475589:web:125c8db9ad40679b0d066c',
    messagingSenderId: '281641475589',
    projectId: 'chat-app-1591c',
    authDomain: 'chat-app-1591c.firebaseapp.com',
    storageBucket: 'chat-app-1591c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCngJBaYA7I7Y5LsjpuHSlZFFF_N1uAbj4',
    appId: '1:281641475589:android:9e504839aa6619460d066c',
    messagingSenderId: '281641475589',
    projectId: 'chat-app-1591c',
    storageBucket: 'chat-app-1591c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6-2ypO-Ppc_l6DOH6zu5ApPXyOO2shGU',
    appId: '1:281641475589:ios:95cec2eb102ec91e0d066c',
    messagingSenderId: '281641475589',
    projectId: 'chat-app-1591c',
    storageBucket: 'chat-app-1591c.appspot.com',
    iosClientId: '281641475589-41245kig27hul9q2f9rc80hk2qtv77ps.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6-2ypO-Ppc_l6DOH6zu5ApPXyOO2shGU',
    appId: '1:281641475589:ios:8ec28dc8ae8518390d066c',
    messagingSenderId: '281641475589',
    projectId: 'chat-app-1591c',
    storageBucket: 'chat-app-1591c.appspot.com',
    iosClientId: '281641475589-af4nqjdg4q7ec54plsispvtpud2af542.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
